# Basic Information 
title: Zhengyang Luo
position: M.S. Student in ECE
affiliation: University of Michigan
affiliation_link: https://ece.engin.umich.edu/
email: "cyruszyluo (at) gmail.com<br>zyluo (at) umich.edu"

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: Zhengyang Luo, University of Michigan, multimodal systems, vision-language models, diffusion models
description: Personal homepage of Zhengyang Luo, M.S. student in ECE at the University of Michigan.
canonical: https://cyrusluo.site/
url: https://cyrusluo.site

# Links 
# If you don't need one of them, you may delete the corresponding line.
github_link: https://github.com/peacewang017
linkedin: https://www.linkedin.com/in/cyrus-luo-6549802ba/

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/avatar.jpg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: true

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: true

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
font: "Serif" # or "Sans Serif"



# Generates sitemap.xml for search engines
plugins:
  - jekyll-sitemap

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
  - vendor/
